NUMPY lec1

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])

In [3]:
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
y = [1,2,3,4]
print(y)
print(type(y))

[1, 2, 3, 4]
<class 'list'>


###ARRAY

In [5]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
x = [1,2,3,4]
y = np.array(x)
print(y)
y

[1 2 3 4]


array([1, 2, 3, 4])

In [7]:
a = np.arange(5,11)
print(a)

[ 5  6  7  8  9 10]


In [8]:
l = []

# for i in range(1,5):
#     int_1 = int(input("enter :"))
#     l.append(int_1)

input_num = [int(x) for x in input("ENTER the no : " ).split()]

for x in input_num:
    l.append(x)


print(np.array(l))

[]


Dimension ARRAY

In [9]:
ar_1d = np.array([1,2,3])
ar_2d = np.array([[1,2,3],[1,2,3]])
ar_3d = np.array([[[1,2,3],[1,2,3],[1,2,3]]])

print(ar_1d)
print(ar_1d.ndim)
print(ar_2d)
print(ar_2d.ndim)
print(ar_3d)
print(ar_3d.ndim)

[1 2 3]
1
[[1 2 3]
 [1 2 3]]
2
[[[1 2 3]
  [1 2 3]
  [1 2 3]]]
3


In [10]:
a = np.array([1,2,3,4],ndmin = 10)
print(a)
print(a.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


SPECIAL NUMPY ARRAY

In [11]:
# Array filled with zeroes

arr_zero = np.zeros(4)
print(arr_zero)

print()
print()

arr_zero1 = np.zeros((4,3))
print(arr_zero1)

[0. 0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# Array Filled with Ones

arr_ones = np.ones(3)
print(arr_ones)

print()
print()

arr_ones1 = np.ones((4,3))
print(arr_ones1)

[1. 1. 1.]


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# empty arr
arr = np.empty(4)
print(arr)

[0. 0. 0. 0.]


In [14]:
#np.arange

x = np.arange(4)
print(x)

y = np.arange(3,9)
print(y)

[0 1 2 3]
[3 4 5 6 7 8]


In [15]:
# Diagonal element filled with ones

x = np.eye(2) #inka square matix banega
print(x)

print()
print()

print(np.eye(4)) #inka square matrix banega

print()
print()

print(np.eye(3,4))

[[1. 0.]
 [0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [16]:
# Array with specified Intervals 

x = np.linspace(0,10,num = 11)
print(x)

print()
print()

print(np.linspace(0,10,5))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


[ 0.   2.5  5.   7.5 10. ]


CREATING NUMPY ARRAY WITH RANDOM NOS

In [17]:
# random nos
a = np.random.rand(4)
print(a)

[0.40191327 0.11247189 0.41399942 0.11988245]


In [18]:
# randn

a = np.random.randn(4)
print(a)

[ 0.38205606  0.22514842  1.18089996 -0.28335558]


In [19]:
# randf

a = np.random.ranf(6)
print(a)

[0.22535419 0.99185049 0.1609583  0.38138818 0.62632939 0.10313534]


In [20]:
# randint

a = np.random.randint(5,20,6)
print(a)

[15 10  8 19  6 10]


DATA TYPE IN NUMPY ARRAYS

In [21]:
a = np.array([1,2,3])
b = np.array(["d","g","h"])
c = np.array([1.0,1.1,1.2])

print(a.dtype)
print(b.dtype)
print(c.dtype)



int32
<U1
float64


In [22]:
# change data type
x = np.array([1,2,3,4],dtype=np.float64)
print(x.dtype)
print(x)


float64
[1. 2. 3. 4.]


In [25]:
# change data type
x = np.array([1,2,3,4],dtype="f")
print(x.dtype)
print(x)

float32
[1. 2. 3. 4.]


In [26]:
# change data type
x = np.array([1,2,3,4])
new = np.float32(x)

print(x.dtype)
print(x)
print(new.dtype)
print(new)


int32
[1 2 3 4]
float32
[1. 2. 3. 4.]


In [28]:
# change data type
x = np.array([1,2,3])
new = x.astype(float)
print(new.dtype)
print(new)

float64
[1. 2. 3.]


Airthmetic Operations

In [29]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

add = np.add(a,b)
subtract = np.subtract(a,b)
multiply = np.multiply(a,b)
divide = np.divide(a,b)
modoulus = np.mod(a,b)
power = np.power(a,b)
reciprocal = np.reciprocal(a)


print(add)
print(subtract)
print(multiply)
print(divide)
print(modoulus)
print(power)
print(reciprocal)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
[0 0 0 0 0]
[   1    4   27  256 3125]
[1 0 0 0 0]


AIRTHMETIC OPERATIONS

In [37]:
a = np.array([2,3,4,5,1])
print(np.min(a))
print(np.max(a))
print(np.argmin(a))
print(np.argmax(a))
print(np.cumsum(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))


1
5
4
3
[ 2  5  9 14 15]
[1.41421356 1.73205081 2.         2.23606798 1.        ]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427  0.84147098]
[-0.41614684 -0.9899925  -0.65364362  0.28366219  0.54030231]


In [42]:
# 2d array  0 means column , 1 means row
x = np.array([[1,2,3],[8,9,5],[2,4,8]])
print(np.max(x,axis=0))
print(np.max(x))

[8 9 8]
9


SHAPE AND RESHAPING IN NUMPY ARRAY

In [43]:
x = np.array([[1,2,3],[1,2,3]])

In [44]:
print(x.shape)

(2, 3)


In [45]:
print(x.reshape(3,2))

[[1 2]
 [3 1]
 [2 3]]


In [51]:
print(x.reshape(6,1))

[[1]
 [2]
 [3]
 [1]
 [2]
 [3]]


In [53]:
# from multidimensional array to 1d array
print(x.reshape(-1))

[1 2 3 1 2 3]


In [55]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a+b)

[2 4 6 8]


Indexing & slicing

In [56]:
a = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [71]:
print(a[0][1][2])

6


In [78]:
a = np.array([1,2,3,4,5,6,7,8,9]);
b = a[1:9:2]
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[2 4 6 8]


Iterating in Numpy array

In [81]:
x = np.array([1,2,3,4,5])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
z = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])

In [85]:
# first way
for i in x:
    print(i)

print()

for i in y:
    for j in i:
        print(j)



print()

for i in z:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5

1
2
3
4
5
6
7
8
9

1
2
3
4
5
6
7
8
9


In [87]:
# way 2

for i in np.nditer(x):
    print(i)

print()
for i in np.nditer(y):
    print(i)

print()
for i in np.nditer(z):
    print(i)

1
2
3
4
5

1
2
3
4
5
6
7
8
9

1
2
3
4
5
6
7
8
9


Copy   vs   View 

In [91]:
x = np.array([1,2,3])
copy = x.copy()
y = np.array([4,5,6])
view = y.view()

copy[1] = 5
print(x)
print(copy)

print()
print()


view[1] = 2
print(y)
print(view)

[1 2 3]
[1 5 3]


[4 2 6]
[4 2 6]


Join & Split

In [93]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = np.concatenate((a,b))

print(c)

[1 2 3 4 5 6]


In [97]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[1,2,3]])

c = np.concatenate((a,b),axis=0)
d = np.concatenate((a,b),axis=1)

print(c)
print()
print()
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]


[[1 2 3 7 8 9]
 [4 5 6 1 2 3]]


In [98]:
# split
a = np.array([1,2,3,4,5,6])
arr = np.array_split(a,3)
print(arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [102]:
a = np.array([[1,2,3],[4,5,6]])
arr =  np.array_split(a,2)
print(arr)
print()
print()

b = np.array_split(a,2,axis=0)
c = np.array_split(a,2,axis=1)
print(b)
print()
print(c)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


[array([[1, 2, 3]]), array([[4, 5, 6]])]

[array([[1, 2],
       [4, 5]]), array([[3],
       [6]])]


Numpy Array Functions

In [106]:
# Search

a = np.array([1,2,3,4,2,3,4,5,2,7,5,2])
ans = np.where(a-5 == 0)
print(ans)


(array([ 7, 10], dtype=int64),)


In [107]:
# Sort Array

x = np.array([5,6,4,2,3,9,7,1,8])
arr = np.sort(x)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [111]:
# Search Sorted Array

x = np.array([5,6,4,2,9,7,1,8])
arr = np.sort(x)
print(arr)

print()

ans = np.searchsorted(arr,3)
print(ans)

[1 2 4 5 6 7 8 9]

2


In [113]:
# Shuffle Array
x = np.array([1,2,3,4,5,6])
np.random.shuffle(x)
print(x)

[1 4 5 2 3 6]


In [116]:
# unique
x = np.array([1,2,3,4,5,5,2,3,4,5])
arr = np.unique(x,return_counts=True,return_index=True)
print(arr)


(array([1, 2, 3, 4, 5]), array([0, 1, 2, 3, 4], dtype=int64), array([1, 2, 2, 2, 3], dtype=int64))


In [120]:
# Insert
a = np.array([1,2,3,5])
print(a)
x = np.insert(a,(3,4),4)
print(x)

[1 2 3 5]
[1 2 3 4 5 4]


In [121]:
# delete

y = np.delete(x,(3,5))
print(y)

[1 2 3 5]


MATRIX FUNCTIONS

In [126]:
# Transpose

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

print()


x = np.transpose(a)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [131]:
# SwapAxes
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

print() 

x = np.swapaxes(a,0,1)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [135]:
# Inverse
a = np.array([[1,5,-5],[4,5,2],[7,18,9]])
print(a)

print()

x = np.linalg.inv(a)
print(x)

[[ 1  5 -5]
 [ 4  5  2]
 [ 7 18  9]]

[[-0.03146853  0.47202797 -0.12237762]
 [ 0.07692308 -0.15384615  0.07692308]
 [-0.12937063 -0.05944056  0.05244755]]


In [141]:
# power
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

print() 

x = np.linalg.matrix_power(a,2)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [142]:
# Determinant

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

print() 

x = np.linalg.det(a)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

0.0


In [143]:
# Standard Deviation

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.std())

2.581988897471611


In [147]:
# Sum
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

45
[12 15 18]
[ 6 15 24]
